env:
  browser: true
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:toml/standard'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars: 1
  toml/padding-line-between-tables: 0
  no-prototype-builtins: 0
overrides:
  - files: ["*.toml"]
    parser: 'toml-eslint-parser'
  - files: ["*.gjson", "*.geojson", "*.json"]
    parser: 'eslint-plugin-json-es'
    extends: 'plugin:eslint-plugin-json-es/recommended'
  - files: ["scripts/*.cjs", "scripts/*.mjs"]
ignorePatterns:
  - layouts/_default/*
  - node_modules/*
  - scripts/**/*.toml
