env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:toml/standard'
  - 'plugin:json/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars: 1
  toml/padding-line-between-tables: 0
overrides:
  - files: ["*.toml"]
    parser: 'toml-eslint-parser'
ignorePatterns:
  - layouts/_default/*


#  ": ["error", { "vars": "all", "args": "after-used", "ignoreRestSiblings": false }]
