extends:
  - stylelint-config-standard
  - stylelint-config-recommended-scss
plugins:
  - stylelint-scss
rules:
  at-rule-no-unknown:
    - null
  scss/at-rule-no-unknown:
   - true
  declaration-block-single-line-max-declarations:
    - null
  color-hex-length:
    - short
    - severity: warning
  block-no-empty:
    - true
    - severity: warning
  at-rule-empty-line-before:
    - null
  alpha-value-notation:
    - number
  font-family-name-quotes:
    - null
  function-url-quotes:
    - null
#  indentation:
#    - null
#  selector-list-comma-newline-after:
#    - null
#  declaration-block-trailing-semicolon:
#    - null
#  declaration-colon-space-after:
#    - null
#  number-leading-zero:
#    - always
#    - severity: warning
#  max-empty-lines:
#    - 1
#    - severity: warning
#  block-opening-brace-space-before:
#    - null
#  block-opening-brace-space-after:
#    - null
#  block-closing-brace-space-before:
#    - null
#  block-closing-brace-space-after:
#    - null
#  declaration-block-semicolon-space-after:
#    - null
#  block-closing-brace-newline-after:
#    - null
#  function-comma-space-after:
#    - null
#  at-rule-name-space-after:
#    - null
#  media-feature-colon-space-after:
#    - null
#  selector-combinator-space-before:
#    - null
#  selector-combinator-space-after:
#    - null
#  value-list-comma-space-after:
#    - null
#  function-whitespace-after:
#    - null
#  no-missing-end-of-source-newline:
#    - null
#  declaration-bang-space-before:
#    - null
