name = "Projektemacher Base"
# Some features require 0.141.0 to include https://gohugo.io/functions/go-template/try/
min_version = "0.146.7"

[author]
  name = "Christian Mahnke"
  homepage = "//christianmahnke.de"

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
  [mediaTypes."application/x-qrcode-template"]
    suffixes = ["json"]
# See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

[outputFormats]

  [outputFormats.qrcode]
    mediaType = "application/x-qrcode-template"
    isPlainText = true
    isHTML = false
    baseName = "qrcode"
    notAlternative = true

  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true


#[module]
#  [module.hugoVersion]
#    extended = true
#    min = '0.146.7'

[security]
  [security.http]
    mediaTypes = ['^application/json$', '^application/json;\s?charset=[uU][tT][fF]-8$', '^application/sparql-results\+json;\s?charset=[uU][tT][fF]-8$']
