name = "Projektemacher Base"
min_version = 0.106

[author]
  name = "Christian Mahnke"
  homepage = "//christianmahnke.de"

  [mediaTypes]
    [mediaTypes."application/geo+json"]
      suffixes = ["geojson", "gjson"]
    [mediaTypes."application/ld+json"]
      suffixes = ["json"]
    [mediaTypes."application/x-qrcode-template"]
      suffixes = ["json"]
  # See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
    [mediaTypes."image/jxl"]
      suffixes = ["jxl"]

  [outputFormats]

    [outputFormats.qrcode]
      mediaType = "application/x-qrcode-template"
      isPlainText = true
      isHTML = false
      baseName = "qrcode"
      notAlternative = true
